apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: AZPostgreDB
  title: Azure Postgre DB creation service
  description: A Workflow to create a new service
  tags:
    - nextjs
    - react
    - javascript
spec:
  owner: cims@company.com
  type: service
  parameters:
    - title: Select Harness Project and Org
      type: object
      properties:
        projectId:
          title: Harness Project ID
          description: Select the Harness Project ID
          type: string
          ui:field: HarnessProjectPicker
          ui:autofocus: true
        organizationId:
          title: Harness Organization ID
          description: Select the Harness Organization ID
          type: string
          ui:field: HarnessAutoOrgPicker
    - title: Service, Environment and Infrastructure Details
      required:
        - service
        - environment
        - infrastructure
      properties:
        service:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Choose the service
            description: Pick one of the service you want to deploy
            placeholder: "Choose a service"
            allowArbitraryValues: true
            path: proxy/harness-api-endpoint/ng/api/servicesV2?page=0&size=100&accountIdentifier=ACCOUNT_ID&orgIdentifier={{parameters.organizationId}}&projectIdentifier={{parameters.projectId}}&includeAllServicesAccessibleAtScope=true
            valueSelector: 'service.name'
            arraySelector: 'data.content'
          environment:
            type: string
            ui:field: SelectFieldFromApi
            ui:options:
              title: Choose the environment
              description: Pick the environment where you want to deploy
              placeholder: "Choose a environment"
              allowArbitraryValues: true
              path: proxy/harness-api-endpoint/ng/api/environmentsV2?page=0&size=100&accountIdentifier=ACCOUNT_ID&orgIdentifier={{parameters.organizationId}}&projectIdentifier={{parameters.projectId}}
              valueSelector: 'environment.name'
              arraySelector: 'data.content'
          infrastructure:
            type: string
            ui:field: SelectFieldFromApi
            ui:options:
              title: Choose the infrastructure
              description: The infrastructure to deploy to (e.g., AWS, GCP, Azure)
              placeholder: "Choose an infrastructure"
              allowArbitraryValues: true
              path: proxy/harness-api-endpoint/ng/api/infrastructures?page=0&size=100&environmentIdentifier=ENV_ID&accountIdentifier=ACCOUNT_ID&orgIdentifier={{parameters.organizationId}}&projectIdentifier={{parameters.projectId}}
              valueSelector: 'infrastructure.name'
              arraySelector: 'data.content'
        # This field is hidden but needed to authenticate the request to trigger the pipeline
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Bootstrapping your new service
      action: trigger:harness-custom-pipeline
      input:
        url: "https://app.harness.io/ng/account/8Xl8tQSaSeyvtccXETil_Q/module/iacm/orgs/CoforgeCIMSPE/projects/CoforgeIDPPE/pipelines/AZStorageaccount/pipeline-studio/?storeType=INLINE"
        inputset:
          resourcegroup_name: ${{ parameters.resourcegroup_name }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
